### ISSUE TITLE
ValueError: batch_size should be a positive integer value, but got batch_size=0

### ISSUE THREAD

**Issue by MeMiracle** [MetaSLAM/SphereVLAD#1]
First of all, thanks for sharing the code. 
I run the code following the steps you recommended and got an error when running
`python train_lcd.py --config-network=config/network/spherevlad.yaml --config-dataset=config/dataset/PITT.yaml`

The error message is as follows:
`INFO - 2023-09-25 16:55:20,614 - logger - Namespace(config_dataset='config/dataset/PITT.yaml', config_network='config/network/spherevlad.yaml')
INFO - 2023-09-25 16:55:20,614 - logger - Loaded network configuration file config/network/spherevlad.yaml
INFO - 2023-09-25 16:55:20,614 - logger - Loaded dataset configuration file config/dataset/PITT.yaml
Runing SphereVLAD
#params of model: 17376
#trainable params of model: 17376
Using dataset: PITT
Load previous pickles
Number of training tuples: 1093
Traceback (most recent call last):
  File "train_lcd.py", line 118, in <module>
    train(cfg, logger, neptune)
  File "train_lcd.py", line 44, in train
    train_loader = make_data_loader(config, gpu_ids, is_train=True)
  File "/home/lanx/Programs/SphereVLAD/dataloader/__init__.py", line 31, in make_data_loader
    loader = DataLoader(dataloader,
  File "/home/lanx/miniconda3/envs/spherevlad/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 350, in __init__
    batch_sampler = BatchSampler(sampler, batch_size, drop_last)
  File "/home/lanx/miniconda3/envs/spherevlad/lib/python3.8/site-packages/torch/utils/data/sampler.py", line 232, in __init__
    raise ValueError("batch_size should be a positive integer value, "
ValueError: batch_size should be a positive integer value, but got batch_size=0
`
How to solve this problem, thanks.

**Comment by ryanzhao9459** [comment]
Hi
In [dataloader/__init__.py](https://github.com/MetaSLAM/SphereVLAD/blob/559d5f46b0f8217874273c78e622f28999200482/dataloader/__init__.py#L32C52-L32C52) the number of batch size is defined as the multiplication of gpu number and the  batch size defined in yaml file.

Please check the gpu number in the first place by
`torch.cuda.device_count()`
